name: Deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      INSTANCE_IP: ${{ secrets.INSTANCE_IP }}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
      USER1_PASSWORD: ${{ secrets.USER1_PASSWORD }}
      USER2_PASSWORD: ${{ secrets.USER2_PASSWORD }}
      USER1_EMAIL: ${{ secrets.USER1_EMAIL }}
      USER2_EMAIL: ${{ secrets.USER2_EMAIL }}
      ACCES_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      ACCESS_TOKEN_EXPIRATION_DAYS: ${{ secrets.ACCESS_TOKEN_EXPIRATION_DAYS }}
      ALLOWED_ORIGINS: ${{ secrets.ALLOWED_ORIGINS }}
      REACT_APP_REDUX_PERSIST_KEY: ${{ secrets.REDUX_PERSIST_KEY }}
      REACT_APP_CURRENCY: ${{ secrets.CURRENCY }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          bash deploy.sh
